<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" href="/favicon.ico" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title><?php if($website_title){ echo $website_title; }?></title>
    <script type="module" crossorigin src="/assets/index.16518c40.js"></script>
    <link rel="stylesheet" href="/assets/index.cf80e917.css">
  </head>
  <body>
    <div id="app"></div>
  </body>
</html>
<?php
if(isset($value)) {
    echo $value;
}
