<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" href="/favicon.ico" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title><?php if($website_title){ echo $website_title; } else { echo "Svelte rocks!";  }?></title>
    <script type="module" crossorigin src="/assets/index.f0fac1ad.js"></script>
    <link rel="stylesheet" href="/assets/index.2362315a.css">
  </head>
  <body>
    <div id="app"></div>
    
  </body>
</html>
